[profile.default]
src = "."
out = "out"
libs = ["lib"]
test = "test"

# Optimizer settings
optimizer = true
optimizer_runs = 200

# EVM version
evm_version = "paris"

# Gas settings
gas_limit = 30_000_000
gas_price = 20_000_000_000

# Chain configuration for Abstract Mainnet
[rpc_endpoints]
abstract = "https://api.mainnet.abs.xyz"

[etherscan]
abstract = { key = "${ABSTRACT_ETHERSCAN_API_KEY}", url = "https://api.abscan.org/api" }

# Testing configuration
[fuzz]
runs = 256
max_test_rejects = 65536
seed = '0x3e8'
dictionary_weight = 40
include_storage = true
include_push_bytes = true

[invariant]
runs = 256
depth = 15
fail_on_revert = false
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true

# Compiler settings
solc_version = "0.8.19"
auto_detect_solc = false
offline = false
use_literal_content = false
bytecode_hash = "none"
cbor_metadata = false
sparse_mode = false
build_info = false
extra_output = ["storageLayout"]
extra_output_files = ["metadata"]

# Dependencies
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/"
]

# Ignore patterns
ignored_error_codes = [
    1878,  # SPDX license identifier not provided
    5574,  # Contract code size exceeds limit
]

# Cache settings
cache = true
cache_path = "cache"
force = false
build_info_path = "build-info"

# Verbosity
verbosity = 2

# Other settings
memory_limit = 33554432
via_ir = false